### ISSUE TITLE
How to implement without Maven?

### ISSUE THREAD

**Issue by marttosc** [Sheigutn/pushbullet-java-8#2]
Hi, I'm trying to implement this on my console application, a project without Maven. I downloaded all the dependencies from the JARs files, but when it compiles I get a lot of errors.

In `ListUtil` class, `fullList` method, I get an error saying that the **`getCursor()`** is not implemented. This call is from `ListResponse`.

Other case that happened is on the `Pushbullet` class on `gson` property. It gave this error:

`The constructor PushbulletContainerPostProcessor(Pushbullet) is undefined`

Could you help me?

**Comment by ghost** [comment]
I had to do this as well. I got everything from this site http://mvnrepository.com/artifact/com.github.sheigutn/pushbullet-java-8/1.3.4

Just go through all the dependencies recursively and download all their dependencies and so on until you reach ones with no dependencies. You get about 23 jars including pushbullet-java-8. Then just all those jars to your build path.
You only really need the dependencies in the compile and provided dependencies sections that are not marked optional, but it's worth considering optional ones and the ones in the testing dependencies section.
My libraries folder for my project looks a bit like this:
- avalon-framework-4.1.5.jar
- avalon-logkit-2.2.1.jar
- commons-codec-1.10.jar
- commons-logging-1.2.jar
- geronimo-jms_1.1_spec-1.1.1.jar
- gson-2.6.2.jar
- gson-fire-1.5.1.jar
- hamcrest-core-1.3.jar
- httpclient-4.5.2.jar
- httpcore-4.4.4.jar
- httpmime-4.5.2.jar
- javax.mail-api-1.5.5.jar
- javax.servlet-api-3.1.0.jar
- javax.websocket-api-1.1.jar
- log4j-api-2.5.jar
- log4j-core-2.5.jar
- mockito-core-1.10.19.jar
- objenesis-2.2.jar
- org.osgi.core-6.0.0.jar
- pushbullet-java-8-1.3.4.jar
- twitter4j-core-4.0.4.jar
- twitter4j-stream-4.0.4.jar
- tyrus-standalone-client-1.12.jar

**Comment by marttosc** [comment]
It's not worked. :disappointed:

Even downloading the JARs dependencies, when compiled throws the same error.

**Comment by Sheigutn** [comment]
I've just created a jar file with all the dependencies. [Download it here.](https://github.com/Sheigutn/pushbullet-java-8/releases/download/1.3.5-SNAPSHOT/pushbullet-java-8-1.3.5-SNAPSHOT.jar)

**Comment by marttosc** [comment]
Now it works! Thanks!
